# map configurations
[map]
    # compatible game-modes
    compatible_game_modes = [
        "sandbox",
        "deathmatch"
    ]

    # list of spawn points
    spawn_points = [
        { location = "Vector(100, 200, 100)", rotation = "Rotator(0, 90, 0)" },
        { location = "Vector(200, 300, 100)", rotation = "Rotator(0, 90, 0)" },
    ]

[custom_data]
    whatever = "anything"
